# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_de_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Tela_Cadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -1, 801, 131))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0681818 rgba(14, 8, 73, 255), stop:0.607955 rgba(28, 17, 145, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LEBANK_label = QtWidgets.QLabel(self.frame)
        self.LEBANK_label.setGeometry(QtCore.QRect(0, 0, 811, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        self.LEBANK_label.setFont(font)
        self.LEBANK_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LEBANK_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.210227 rgba(255, 255, 0, 255), stop:0.778409 rgba(255, 255, 117, 255));")
        self.LEBANK_label.setObjectName("LEBANK_label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 90, 811, 381))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.nome_line = QtWidgets.QLineEdit(self.frame_2)
        self.nome_line.setGeometry(QtCore.QRect(210, 70, 391, 20))
        self.nome_line.setObjectName("nome_line")
        self.nome_label = QtWidgets.QLabel(self.frame_2)
        self.nome_label.setGeometry(QtCore.QRect(130, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nome_label.setFont(font)
        self.nome_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nome_label.setObjectName("nome_label")
        self.sobrenome_label = QtWidgets.QLabel(self.frame_2)
        self.sobrenome_label.setGeometry(QtCore.QRect(90, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sobrenome_label.setFont(font)
        self.sobrenome_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sobrenome_label.setObjectName("sobrenome_label")
        self.sobrenome_line = QtWidgets.QLineEdit(self.frame_2)
        self.sobrenome_line.setGeometry(QtCore.QRect(210, 120, 391, 20))
        self.sobrenome_line.setObjectName("sobrenome_line")
        self.cpf_label = QtWidgets.QLabel(self.frame_2)
        self.cpf_label.setGeometry(QtCore.QRect(140, 160, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cpf_label.setFont(font)
        self.cpf_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cpf_label.setObjectName("cpf_label")
        self.cpf_line = QtWidgets.QLineEdit(self.frame_2)
        self.cpf_line.setGeometry(QtCore.QRect(210, 170, 391, 20))
        self.cpf_line.setObjectName("cpf_line")
        self.confirmar_botao = QtWidgets.QPushButton(self.frame_2)
        self.confirmar_botao.setGeometry(QtCore.QRect(150, 280, 211, 51))
        self.confirmar_botao.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.confirmar_botao.setObjectName("confirmar_botao")
        self.senha_label = QtWidgets.QLabel(self.frame_2)
        self.senha_label.setGeometry(QtCore.QRect(130, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.senha_label.setFont(font)
        self.senha_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.senha_label.setObjectName("senha_label")
        self.senha_line = QtWidgets.QLineEdit(self.frame_2)
        self.senha_line.setGeometry(QtCore.QRect(210, 220, 391, 20))
        self.senha_line.setObjectName("senha_line")
        self.voltar_botao = QtWidgets.QPushButton(self.frame_2)
        self.voltar_botao.setGeometry(QtCore.QRect(460, 280, 211, 51))
        self.voltar_botao.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.voltar_botao.setObjectName("voltar_botao")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 460, 811, 121))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0681818 rgba(14, 8, 73, 255), stop:0.607955 rgba(28, 17, 145, 255));\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro"))
        self.LEBANK_label.setText(_translate("MainWindow", "                                                 LEBANK"))
        self.nome_label.setText(_translate("MainWindow", "Nome:"))
        self.sobrenome_label.setText(_translate("MainWindow", "Sobrenome:"))
        self.cpf_label.setText(_translate("MainWindow", "CPF:"))
        self.confirmar_botao.setText(_translate("MainWindow", "CONFIRMAR"))
        self.senha_label.setText(_translate("MainWindow", "Senha:"))
        self.voltar_botao.setText(_translate("MainWindow", "VOLTAR"))

