# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_de_transferir.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Tela_Transferencia(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 61))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0681818 rgba(14, 8, 73, 255), stop:0.607955 rgba(28, 17, 145, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LEBANK_label = QtWidgets.QLabel(self.frame)
        self.LEBANK_label.setGeometry(QtCore.QRect(0, 0, 811, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        self.LEBANK_label.setFont(font)
        self.LEBANK_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LEBANK_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.210227 rgba(255, 255, 0, 255), stop:0.778409 rgba(255, 255, 117, 255));")
        self.LEBANK_label.setObjectName("LEBANK_label")
        self.saldo_label = QtWidgets.QLabel(self.frame)
        self.saldo_label.setGeometry(QtCore.QRect(580, 30, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saldo_label.setFont(font)
        self.saldo_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(19, 11, 98);")
        self.saldo_label.setObjectName("saldo_label")
        self.saldo_line = QtWidgets.QLineEdit(self.frame)
        self.saldo_line.setGeometry(QtCore.QRect(630, 30, 141, 21))
        self.saldo_line.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(23, 14, 121);")
        self.saldo_line.setObjectName("saldo_line")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 811, 511))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.numero_da_conta_do_destinatario_line = QtWidgets.QLineEdit(self.frame_2)
        self.numero_da_conta_do_destinatario_line.setGeometry(QtCore.QRect(270, 30, 131, 20))
        self.numero_da_conta_do_destinatario_line.setObjectName("numero_da_conta_do_destinatario_line")
        self.numero_da_conta_do_destinatario_label = QtWidgets.QLabel(self.frame_2)
        self.numero_da_conta_do_destinatario_label.setGeometry(QtCore.QRect(20, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numero_da_conta_do_destinatario_label.setFont(font)
        self.numero_da_conta_do_destinatario_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.numero_da_conta_do_destinatario_label.setObjectName("numero_da_conta_do_destinatario_label")
        self.nome_do_destinatario_label = QtWidgets.QLabel(self.frame_2)
        self.nome_do_destinatario_label.setGeometry(QtCore.QRect(10, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nome_do_destinatario_label.setFont(font)
        self.nome_do_destinatario_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nome_do_destinatario_label.setObjectName("nome_do_destinatario_label")
        self.nome_do_destinatario_line = QtWidgets.QLineEdit(self.frame_2)
        self.nome_do_destinatario_line.setGeometry(QtCore.QRect(180, 80, 391, 20))
        self.nome_do_destinatario_line.setObjectName("nome_do_destinatario_line")
        self.voltar_botao = QtWidgets.QPushButton(self.frame_2)
        self.voltar_botao.setGeometry(QtCore.QRect(470, 280, 211, 51))
        self.voltar_botao.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.voltar_botao.setObjectName("voltar_botao")
        self.valor_a_ser_transferido_label = QtWidgets.QLabel(self.frame_2)
        self.valor_a_ser_transferido_label.setGeometry(QtCore.QRect(170, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.valor_a_ser_transferido_label.setFont(font)
        self.valor_a_ser_transferido_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valor_a_ser_transferido_label.setObjectName("valor_a_ser_transferido_label")
        self.valor_a_ser_transferido_line = QtWidgets.QLineEdit(self.frame_2)
        self.valor_a_ser_transferido_line.setGeometry(QtCore.QRect(350, 190, 131, 20))
        self.valor_a_ser_transferido_line.setObjectName("valor_a_ser_transferido_line")
        self.buscar_botao = QtWidgets.QPushButton(self.frame_2)
        self.buscar_botao.setGeometry(QtCore.QRect(440, 30, 81, 21))
        self.buscar_botao.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.buscar_botao.setObjectName("buscar_botao")
        self.cpf_do_destinatario_label = QtWidgets.QLabel(self.frame_2)
        self.cpf_do_destinatario_label.setGeometry(QtCore.QRect(20, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cpf_do_destinatario_label.setFont(font)
        self.cpf_do_destinatario_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cpf_do_destinatario_label.setObjectName("cpf_do_destinatario_label")
        self.cpf_do_destinatario_line = QtWidgets.QLineEdit(self.frame_2)
        self.cpf_do_destinatario_line.setGeometry(QtCore.QRect(180, 140, 391, 20))
        self.cpf_do_destinatario_line.setObjectName("cpf_do_destinatario_line")
        self.transferir_botao = QtWidgets.QPushButton(self.frame_2)
        self.transferir_botao.setGeometry(QtCore.QRect(140, 280, 211, 51))
        self.transferir_botao.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.transferir_botao.setObjectName("transferir_botao")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 370, 811, 181))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0681818 rgba(14, 8, 73, 255), stop:0.607955 rgba(28, 17, 145, 255));\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transferencia"))
        self.LEBANK_label.setText(_translate("MainWindow", "                                                 LEBANK"))
        self.saldo_label.setText(_translate("MainWindow", "Saldo:"))
        self.numero_da_conta_do_destinatario_label.setText(_translate("MainWindow", "Número da conta do destinatário:"))
        self.nome_do_destinatario_label.setText(_translate("MainWindow", "Nome do destinatário:"))
        self.voltar_botao.setText(_translate("MainWindow", "Voltar"))
        self.valor_a_ser_transferido_label.setText(_translate("MainWindow", "Valor à ser transferido:"))
        self.buscar_botao.setText(_translate("MainWindow", "Buscar"))
        self.cpf_do_destinatario_label.setText(_translate("MainWindow", "CPF do destinatário:"))
        self.transferir_botao.setText(_translate("MainWindow", "Transferir"))

