# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Tela_Principal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 61))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0681818 rgba(14, 8, 73, 255), stop:0.607955 rgba(28, 17, 145, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LEBANK_label = QtWidgets.QLabel(self.frame)
        self.LEBANK_label.setGeometry(QtCore.QRect(0, 0, 801, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        self.LEBANK_label.setFont(font)
        self.LEBANK_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LEBANK_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.210227 rgba(255, 255, 0, 255), stop:0.778409 rgba(255, 255, 117, 255));")
        self.LEBANK_label.setAlignment(QtCore.Qt.AlignCenter)
        self.LEBANK_label.setObjectName("LEBANK_label")
        self.saldo_label = QtWidgets.QLabel(self.frame)
        self.saldo_label.setGeometry(QtCore.QRect(580, 30, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saldo_label.setFont(font)
        self.saldo_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(19, 11, 98);")
        self.saldo_label.setObjectName("saldo_label")
        self.saldo_line = QtWidgets.QLineEdit(self.frame)
        self.saldo_line.setGeometry(QtCore.QRect(630, 30, 141, 21))
        self.saldo_line.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(23, 14, 121);")
        self.saldo_line.setObjectName("saldo_line")
        self.titular_label = QtWidgets.QLabel(self.frame)
        self.titular_label.setGeometry(QtCore.QRect(10, 30, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titular_label.setFont(font)
        self.titular_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(19, 11, 98);")
        self.titular_label.setObjectName("titular_label")
        self.titular_line = QtWidgets.QLineEdit(self.frame)
        self.titular_line.setGeometry(QtCore.QRect(70, 30, 281, 21))
        self.titular_line.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(23, 14, 121);")
        self.titular_line.setObjectName("titular_line")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(-10, 60, 811, 451))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0681818 rgba(14, 8, 73, 255), stop:0.607955 rgba(28, 17, 145, 255));\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.ver_extrato_botao = QtWidgets.QPushButton(self.frame_3)
        self.ver_extrato_botao.setGeometry(QtCore.QRect(150, 30, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ver_extrato_botao.setFont(font)
        self.ver_extrato_botao.setMouseTracking(False)
        self.ver_extrato_botao.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);")
        self.ver_extrato_botao.setObjectName("ver_extrato_botao")
        self.transferir_botao = QtWidgets.QPushButton(self.frame_3)
        self.transferir_botao.setGeometry(QtCore.QRect(530, 30, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.transferir_botao.setFont(font)
        self.transferir_botao.setMouseTracking(False)
        self.transferir_botao.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);")
        self.transferir_botao.setObjectName("transferir_botao")
        self.sacar_botao = QtWidgets.QPushButton(self.frame_3)
        self.sacar_botao.setGeometry(QtCore.QRect(150, 220, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sacar_botao.setFont(font)
        self.sacar_botao.setMouseTracking(False)
        self.sacar_botao.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);")
        self.sacar_botao.setObjectName("sacar_botao")
        self.depositar_botao = QtWidgets.QPushButton(self.frame_3)
        self.depositar_botao.setGeometry(QtCore.QRect(530, 220, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.depositar_botao.setFont(font)
        self.depositar_botao.setMouseTracking(False)
        self.depositar_botao.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);")
        self.depositar_botao.setObjectName("depositar_botao")
        self.sair_botao = QtWidgets.QPushButton(self.frame_3)
        self.sair_botao.setGeometry(QtCore.QRect(350, 370, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sair_botao.setFont(font)
        self.sair_botao.setMouseTracking(False)
        self.sair_botao.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);")
        self.sair_botao.setObjectName("sair_botao")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Principal"))
        self.LEBANK_label.setText(_translate("MainWindow", "LEBANK"))
        self.saldo_label.setText(_translate("MainWindow", "Saldo:"))
        self.titular_label.setText(_translate("MainWindow", "Titular:"))
        self.ver_extrato_botao.setText(_translate("MainWindow", "Ver extrato"))
        self.transferir_botao.setText(_translate("MainWindow", "Transferir"))
        self.sacar_botao.setText(_translate("MainWindow", "Sacar"))
        self.depositar_botao.setText(_translate("MainWindow", "Depositar"))
        self.sair_botao.setText(_translate("MainWindow", "Sair"))

