# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_de_extrato.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Tela_Extrato(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LEBANK_label = QtWidgets.QLabel(self.centralwidget)
        self.LEBANK_label.setGeometry(QtCore.QRect(0, 0, 811, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        self.LEBANK_label.setFont(font)
        self.LEBANK_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LEBANK_label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(28, 17, 145);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.210227 rgba(255, 255, 0, 255), stop:0.778409 rgba(255, 255, 117, 255));")
        self.LEBANK_label.setObjectName("LEBANK_label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 20, 811, 551))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.numero_line = QtWidgets.QLineEdit(self.frame_2)
        self.numero_line.setGeometry(QtCore.QRect(90, 10, 131, 20))
        self.numero_line.setObjectName("numero_line")
        self.numero_label = QtWidgets.QLabel(self.frame_2)
        self.numero_label.setGeometry(QtCore.QRect(20, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numero_label.setFont(font)
        self.numero_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.numero_label.setObjectName("numero_label")
        self.titular_label = QtWidgets.QLabel(self.frame_2)
        self.titular_label.setGeometry(QtCore.QRect(260, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titular_label.setFont(font)
        self.titular_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titular_label.setObjectName("titular_label")
        self.titular_line = QtWidgets.QLineEdit(self.frame_2)
        self.titular_line.setGeometry(QtCore.QRect(320, 10, 391, 20))
        self.titular_line.setObjectName("titular_line")
        self.saldo_label = QtWidgets.QLabel(self.frame_2)
        self.saldo_label.setGeometry(QtCore.QRect(30, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saldo_label.setFont(font)
        self.saldo_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saldo_label.setObjectName("saldo_label")
        self.saldo_line = QtWidgets.QLineEdit(self.frame_2)
        self.saldo_line.setGeometry(QtCore.QRect(80, 60, 151, 20))
        self.saldo_line.setObjectName("saldo_line")
        self.voltar_botao = QtWidgets.QPushButton(self.frame_2)
        self.voltar_botao.setGeometry(QtCore.QRect(310, 470, 211, 51))
        self.voltar_botao.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.voltar_botao.setObjectName("voltar_botao")
        self.limite_label = QtWidgets.QLabel(self.frame_2)
        self.limite_label.setGeometry(QtCore.QRect(260, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.limite_label.setFont(font)
        self.limite_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.limite_label.setObjectName("limite_label")
        self.limite_line = QtWidgets.QLineEdit(self.frame_2)
        self.limite_line.setGeometry(QtCore.QRect(320, 59, 391, 21))
        self.limite_line.setObjectName("limite_line")
        self.historico_label = QtWidgets.QLabel(self.frame_2)
        self.historico_label.setGeometry(QtCore.QRect(370, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.historico_label.setFont(font)
        self.historico_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.historico_label.setObjectName("historico_label")
        self.historico_line = QtWidgets.QTextEdit(self.frame_2)
        self.historico_line.setGeometry(QtCore.QRect(200, 110, 421, 361))
        self.historico_line.setObjectName("historico_line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extrato"))
        self.LEBANK_label.setText(_translate("MainWindow", "                                                 LEBANK"))
        self.numero_label.setText(_translate("MainWindow", "Número:"))
        self.titular_label.setText(_translate("MainWindow", "Titular:"))
        self.saldo_label.setText(_translate("MainWindow", "Saldo:"))
        self.voltar_botao.setText(_translate("MainWindow", "Voltar"))
        self.limite_label.setText(_translate("MainWindow", "Limite:"))
        self.historico_label.setText(_translate("MainWindow", "Histórico"))

