from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from cadastro import Pessoa, Cadastro
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 570)

        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(110, 300, 481, 241))
        self.label_11.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(250, 510, 141, 20))
        self.lineEdit_7.setStyleSheet("border-radius:5px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 480, 331, 20))
        self.lineEdit_5.setStyleSheet("border-radius:5px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 260, 821, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 370, 81, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(110, 30, 481, 211))
        self.label_10.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 310, 141, 20))
        self.lineEdit_8.setStyleSheet("border-radius:5px;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 47, 13))
        self.label_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(120, 140, 101, 20))
        self.label_4.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 50, 47, 13))
        self.label.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(120, 480, 47, 13))
        self.label_7.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(120, 310, 47, 20))
        self.label_9.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(120, 450, 47, 13))
        self.label_6.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(310, 200, 81, 31))
        self.pushButton.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(120, 510, 101, 20))
        self.label_8.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 110, 47, 20))
        self.label_3.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 80, 331, 20))
        self.lineEdit_2.setStyleSheet("border-radius:5px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 450, 331, 20))
        self.lineEdit_6.setStyleSheet("border-radius:5px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 140, 141, 20))
        self.lineEdit_4.setStyleSheet("border-radius:5px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 110, 141, 20))
        self.lineEdit_3.setStyleSheet("border-radius:5px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(250, 50, 331, 20))
        self.lineEdit.setStyleSheet("border-radius:5px;")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.cad = Cadastro()

        self.pushButton.clicked.connect(self.botaoCadastra)
        self.pushButton_2.clicked.connect(self.botaoBusca)

    def botaoCadastra(self):
        nome = self.lineEdit.text()
        endereco = self.lineEdit_2.text()
        cpf = self.lineEdit_3.text()
        nascimento = self.lineEdit_4.text()

        if nome != "" and endereco != "" and cpf != "" and nascimento != "":
            pessoa = Pessoa(nome, endereco, cpf, nascimento)
            if self.cad.cadastra(pessoa):
                QMessageBox.information(None, "POO2", "Cadastro realizado")
                self.lineEdit.setText("")
                self.lineEdit_2.setText("")
                self.lineEdit_3.setText("")
                self.lineEdit_4.setText("")
            else:
                QMessageBox.information(None, "POO2", "O cpf ja existe")
        else:
            QMessageBox.information(None, "POO2", "Todas as informações devem ser preenchidas")

    def botaoBusca(self):
        cpf = self.lineEdit_8.text()
        pessoa = self.cad.busca(cpf)

        if pessoa:
            self.lineEdit_6.setText(pessoa.nome)
            self.lineEdit_5.setText(pessoa.endereco)
            self.lineEdit_7.setText(pessoa.nascimento)
        else:
            QMessageBox.information(None, "POO2", "Cpf não encontrado")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "Buscar"))
        self.label_2.setText(_translate("Form", "Endereço"))
        self.label_4.setText(_translate("Form", "Data de Nascimento"))
        self.label.setText(_translate("Form", "Nome"))
        self.label_7.setText(_translate("Form", "Endereço"))
        self.label_9.setText(_translate("Form", "CPF"))
        self.label_6.setText(_translate("Form", "Nome"))
        self.pushButton.setText(_translate("Form", "Cadastrar"))
        self.label_8.setText(_translate("Form", "Data de Nascimento"))
        self.label_3.setText(_translate("Form", "CPF"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
